### ISSUE TITLE
'Esc' makes Message disappear but does not end Insertmode

### ISSUE THREAD

**Issue by dase78** [jabbalaci/micro-plugins#2]
This is a very nice little Plugin. But one thing keeps me from using it, when I am in Insertmode and the message appears and I (accidently perhaps) hit 'Esc', the REPLACE-indicator disappears but of course the Insertmode is not ended.

**Comment by jabbalaci** [comment]
What should happen when you press the ESC key? Choose:
1) Nothing. You remain in replace mode and the REPLACE-indicator remains visible.
2) Quit replace mode and the REPLACE-indicator disappears.

**Comment by dase78** [comment]
Actually good question. In first place I thought (1). (2) could probably feel more intuitive.

To be on the safe side I would prefer (1).

**Comment by jabbalaci** [comment]
Option (1) is done. You can try it.

**Comment by dase78** [comment]
Works perfect. Also the little message when hitting Esc is good. Comes to my default plugins now, thank's a lot! And nice Christmas (if you celebrate it). ;)

**Comment by jabbalaci** [comment]
I'm glad you like it. Thanks for the improvement idea. Merry Christmas to you too!
